cart/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.view_cart, name='view_cart'),
    path('add/<item_id>/', views.add_to_cart, name='add_to_cart'),
    path('adjust_cart/<item_id>/', views.adjust_cart, name='adjust_cart'),
    path('delete/<item_id>/', views.delete_from_cart, name='delete_from_cart'),
]

products/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from . import views
from .views import ProductListView, CategoryView, ReviewView

app_name = 'products'

urlpatterns = [
    path('', ProductListView.as_view(), name='products'),
    path('category/<str:slug>/', CategoryView, name='category'),
    path('<int:product_id>/', views.product_detail, name='product_detail'),
    path('add/', views.add_product, name='add_product'),
    path('edit/<int:product_id>', views.edit_product, name='edit_product'),
    path('delete/<int:product_id>', views.delete_product,
         name='delete_product'),
    path('review_product/<int:product_id>/<int:order_id>/',
         login_required(ReviewView.as_view()), name='review_product'),
    path('show_reviews/', views.show_reviews, name='show_reviews'),
    path('approve_review/<int:product_id>/<int:review_id>/',
         views.approve_review, name='approve_review'),
]

profiles/urls.py
from django.urls import path
from . import views

app_name = 'profile'

urlpatterns = [
    path('', views.profile, name='profile'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    path('shipping_addresses/', views.shipping_addresses,
         name='shipping_addresses'),
    path('add_address/', views.add_address, name='add_address'),
    path('delete_address/<int:id>/', views.delete_address,
         name='delete_address'),
    path('edit_address/<int:id>/', views.edit_address,
         name='edit_address'),
    path('orders/', views.orders, name='orders'),
    path('order_details/<int:order_id>/', views.order_details,
         name='order_details'),
]

t_studio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('core.urls')),
    path('products/', include(('products.urls'), namespace='products')),
    path('cart/', include('cart.urls')),
    path('checkout/', include('checkout.urls')),
    path('profile/', include(('profiles.urls'), namespace='profile')),
    path('contact/', include('contact.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = 't_studio.views.handler404'
handler500 = 't_studio.views.handler500'

profiles/models.py
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.contrib.auth.models import User


class UserProfile(models.Model):
    """
    A user profile model
    """
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=40, null=True, blank=True)
    last_name = models.CharField(max_length=100, null=True, blank=True)
    phone_number = models.CharField(max_length=20, null=True, blank=True)

    def __str__(self):
        return self.user.username


class UserAddress(models.Model):

    COUNTIES = [
        ('', 'Choose a county *'),
        ('carlow', 'Carlow'),
        ('cavan', 'Cavan'),
        ('clare', 'Clare'),
        ('cork', 'Cork'),
        ('donegal', 'Donegal'),
        ('dublin', 'Dublin'),
        ('galway', 'Galway'),
        ('kerry', 'Kerry'),
        ('kildare', 'Kildare'),
        ('kilkenny', 'Kilkenny'),
        ('laois', 'Laois'),
        ('leitrim', 'Leitrim'),
        ('limerick', 'Limerick'),
        ('longford', 'Longford'),
        ('louth', 'Louth'),
        ('mayo', 'Mayo'),
        ('meath', 'Meath'),
        ('monaghan', 'Monaghan'),
        ('offaly', 'Offaly'),
        ('roscommon', 'Roscommon'),
        ('sligo', 'Sligo'),
        ('tipperary', 'Tipperary'),
        ('waterford', 'Waterford'),
        ('westmeath', 'Westmeath'),
        ('wexford', 'Wexford'),
        ('wicklow', 'Wicklow')
    ]

    username = models.ForeignKey(UserProfile, on_delete=models.CASCADE,
                                 related_name='addresses')
    profile_street_address1 = models.CharField(
        max_length=80, null=True, blank=True)
    profile_street_address2 = models.CharField(
        max_length=80, null=True, blank=True)
    profile_city = models.CharField(max_length=40, null=True, blank=True)
    profile_county = models.CharField(
        max_length=80, choices=COUNTIES, null=True, blank=True)
    profile_postcode = models.CharField(max_length=20, null=True, blank=True)
    profile_country = models.CharField(max_length=50, default='IE')
    is_default = models.BooleanField(default=False)

    def __str__(self):
        return str(self.username)

    class Meta:
        verbose_name_plural = 'User Addresses'


@receiver(post_save, sender=User)
def create_or_update_user_profile(sender, instance, created, **kwargs):
    """
    Create or update the user profile
    """
    if created:
        UserProfile.objects.create(user=instance)
    # Existing users: just save the profile
    instance.userprofile.save()

profiles/forms.py
from django import forms
from crispy_forms.helper import FormHelper
from .models import UserProfile, UserAddress


class ProfileForm(forms.ModelForm):
    """User account form to edit base information """
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper(self)

    first_name = forms.CharField(max_length=50)
    last_name = forms.CharField(max_length=50)
    phone_number = forms.CharField(max_length=15)

    class Meta:
        model = UserProfile
        fields = ['first_name', 'last_name', 'phone_number']


class AddressForm(forms.ModelForm):
    """Address form to change shipping information"""
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.fields['profile_street_address1'].required = True
        self.fields['profile_city'].required = True
        self.fields['profile_county'].required = True

        placeholders = {
                'profile_street_address1': 'Street Address Line 1',
                'profile_street_address2': 'Street Address Line 2',
                'profile_city': 'City',
                'profile_postcode': 'Postcode',
                'profile_country': 'Ireland',
                'is_default': 'Set as default address',
            }

        self.fields['profile_country'].widget.attrs['disabled'] = True
        for field in self.fields:
            if field != 'profile_county':
                if self.fields[field].required:
                    placeholder = f'{placeholders[field]} *'
                else:
                    placeholder = placeholders[field]
                self.fields[field].widget.attrs['placeholder'] = placeholder
            self.fields[field].label = False
        self.fields['is_default'].label = 'Set as default address'

    class Meta:
        model = UserAddress
        exclude = ('user',)
        fields = ['profile_street_address1', 'profile_street_address2',
                  'profile_city', 'profile_county',
                  'profile_postcode', 'profile_country',
                  'is_default']

profiles/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.contrib import messages
from django.contrib.auth.decorators import login_required

from .models import UserProfile, UserAddress
from checkout.models import Order
from .forms import ProfileForm, AddressForm


@login_required
def profile(request):
    """ Display the user's profile. """
    profile = get_object_or_404(UserProfile, user=request.user)
    template = 'profiles/profile.html'
    context = {
        'profile': profile,
    }
    return render(request, template, context)


@login_required
def edit_profile(request):
    """ Edit profile information """
    profile = get_object_or_404(UserProfile, user=request.user)
    form = ProfileForm(instance=profile)
    if request.POST:
        form = ProfileForm(request.POST, instance=profile)
        if form.is_valid():
            form.save()
            messages.success(request,
                             'Your profile has been updated',
                             extra_tags='flag')
        else:
            messages.error(
                request, 'Update failed. Please ensure the form is valid.')
        return redirect('profile:profile')
    else:
        form = ProfileForm(instance=profile)
        context = {
            'form': form
        }
        template = 'profiles/edit_profile.html'
        return render(request, template, context)


@login_required
def shipping_addresses(request):
    """ Display the user's shipping addresses"""
    username = get_object_or_404(UserProfile, user=request.user)
    addresses = UserAddress.objects.filter(
        username_id=username.id).order_by('-is_default')
    if addresses.exists():
        template = 'profiles/shipping_addresses.html'
    else:
        return redirect('profile:add_address')
    context = {
        'addresses': addresses,
    }
    return render(request, template, context)


@login_required
def add_address(request):
    """ Add new shipping address """
    username = get_object_or_404(UserProfile, user=request.user)
    all_addresses = UserAddress.objects.filter(username_id=username.id)
    if request.method == 'POST':
        form = AddressForm(request.POST)
        if form.is_valid():
            # Check if user wants to save this shipping address
            #  as default or if user has no addresses yet
            if form.cleaned_data[
                    'is_default'] is True or not all_addresses.exists():
                is_default = True
                for a in all_addresses:
                    a.is_default = False
                    a.save()
            else:
                is_default = False

            address = UserAddress.objects.create(
                username=username,
                profile_street_address1=form.cleaned_data[
                    'profile_street_address1'],
                profile_street_address2=form.cleaned_data[
                    'profile_street_address2'],
                profile_city=form.cleaned_data[
                    'profile_city'],
                profile_county=form.cleaned_data[
                    'profile_county'],
                profile_postcode=form.cleaned_data[
                    'profile_postcode'],
                profile_country='IE',
                is_default=is_default
            )
            address.save()
            messages.success(request,
                             'Shipping address has been added successfully',
                             extra_tags='flag')
            return redirect('profile:shipping_addresses')
        else:
            messages.error(request, 'Please ensure the form is valid.')
    else:
        form = AddressForm()
        form.fields['profile_country'].initial = 'Ireland'
        template = 'profiles/add_address.html'
        context = {
            'form': form,
        }
        return render(request, template, context)


@login_required
def delete_address(request, id):
    """ Delete shipping address """
    user = get_object_or_404(UserProfile, user=request.user)
    address = UserAddress.objects.get(id=id, username_id=user.id)
    delete_address = request.GET.get('delete_address')
    if delete_address == 'true':
        address.delete()
        messages.success(request,
                         "Your address has been deleted.",
                         extra_tags='flag')
        return redirect('profile:shipping_addresses')
    else:
        template = 'profiles/delete_address.html'
        context = {
            'address': address,
            'id': address.id,
            'flag': True,
        }
        return render(request, template, context)


@login_required
def edit_address(request, id):
    """ Edit shipping address """
    user = get_object_or_404(UserProfile, user=request.user)
    address = UserAddress.objects.get(id=id, username_id=user.id)
    all_addresses = UserAddress.objects.filter(username_id=user.id)

    if request.method == 'POST':
        form = AddressForm(request.POST, instance=address)
        if form.is_valid():
            # Check if user wants to save
            # this shipping address as default
            if form.cleaned_data['is_default'] is True:
                address.is_default = True
                for a in all_addresses:
                    a.is_default = False
                    a.save()
            else:
                address.is_default = False
            address.profile_country = 'IE'
            form.save()
            messages.success(request, 'Successfully updated address!',
                             extra_tags='flag')
            return redirect(reverse('profile:shipping_addresses'))
        else:
            messages.error(request,
                           'Failed to update address.'
                           'Please ensure the form is valid.')
    else:
        address.profile_country = 'Ireland'
        form = AddressForm(instance=address)
        template = 'profiles/edit_address.html'
        context = {
            'form': form,
            'address': address,
        }
        return render(request, template, context)


@login_required
def orders(request):
    """ Display the user's orders"""
    username = get_object_or_404(UserProfile, user=request.user)
    orders = Order.objects.filter(
        user_profile_id=username.id).order_by('-date')
    template = 'profiles/orders.html'
    context = {
        'orders': orders,
    }
    return render(request, template, context)


@login_required
def order_details(request, order_id):
    """ Display the order details"""
    order = get_object_or_404(Order, id=order_id)
    template = 'profiles/order_details.html'
    context = {
        'order': order,
    }
    return render(request, template, context)

profiles/templates/profiles/delete_address.html
{% extends "base.html" %}
{% load static %}

{% block extra_css %}
    <link rel="stylesheet" href="{% static 'profiles/css/profile.css' %}">
{% endblock %}

{% block page_header %}
<div class="container header-container">
    <div class="row text-center">
        <div class="col-12 mt-2 my-auto py-2">
            <h3 class="top-products-link">My Profile</h3>
            <hr> 
        </div>
    </div>
</div>    
{% endblock %}

{% block content %}
<div class="container main text-center">
    <div class="row">        
        {% include 'includes/profile-nav.html' %}   
        <div class="col-12 col-lg-6 ml-lg-3 profile-main">
            <div class="container">                
                <div class="row">
                    <div class="col-12">
                        <h4 class="profile-header mb-3">Are you sure you want to delete this address?</h4>
                        <div>                                    
                            <p>{{ address.profile_street_address1 }}</p>
                            {% if address.profile.street_address2 %}
                                <p>{{ address.profile.street_address2 }}</p>
                            {% endif %}
                            <p>{{ address.profile_city }}</p>
                            <p>{{ address.profile_county }}</p>
                            {% if address.profile.postcode %}
                                <p> {{ address.profile_postcode }}</p>
                            {% endif %}
                            {% if address.profile_country == 'IE' %}
                                <p>Ireland</p>
                            {% endif %} 
                            </div>        
                            <a href="{% url 'profile:delete_address' address.id %}?delete_address=true"  class="btn btn-basic">Delete address</a>
                            <span type="button" class="btn btn-cancel ml-3" onclick="window.history.back()">Cancel</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

profiles/templates/profiles/edit_address.html
{% extends "base.html" %}
{% load static %}

{% block extra_css %}
    <link rel="stylesheet" href="{% static 'profiles/css/profile.css' %}">
{% endblock %}

{% block page_header %}
    <div class="container header-container">
        <div class="row text-center">
            <div class="col-12 mt-2 my-auto py-2">
                <h3 class="top-products-link">My Profile</h3>
                <hr>
            </div>
        </div>
    </div>
{% endblock %}

{% block content %}
<div class="container main text-center">
    <div class="row">
        {% include 'includes/profile-nav.html' %}
        <div class="col-12 col-lg-6 profile-main">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <h4 class="profile-header mb-3">Edit Shipping Address</h4>
                        <form class="mt-3 mb-3" action="{% url 'profile:edit_address' address.id %}" method="POST" id="edit-address-form">
                            {% csrf_token %}
                            {{ form | crispy }}
                            <button type="submit" class="btn btn-basic">Edit address</button>
                            <span class="btn btn-cancel ml-3" onclick="window.history.back()">Cancel</span>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

{% block postloadjs %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'profiles/js/countyfield.js' %}"></script>
    <script type="text/javascript" src="{% static 'profiles/js/remove_disabled.js' %}"></script>
{% endblock %}

profiles/templates/profiles/order-total.html
<h6 class="text-black"><strong>Total: €{{ order.order_total }}</strong></h6>
<h6 class="text-black"><strong>Shipping costs: €{{ order.shipping_cost }}</strong></h6>
<h5 class="text-black"><strong>Grand Total: €{{ order.grand_total }}</strong></h5>

profiles/templates/profiles/order_details.html
{% extends "base.html" %}
{% load static %}
{% load cart_tools %}

{% block extra_css %}
    <link rel="stylesheet" href="{% static 'profiles/css/profile.css' %}">
{% endblock %}

{% block page_header %}
    <div class="container header-container">
        <div class="row text-center">
            <div class="col-12 mt-2 my-auto py-2">
                <h3 class="top-products-link">My Profile</h3>
                <hr> 
            </div>
        </div>
    </div>    
{% endblock %}

{% block content %}
<div class="container main text-center">
    <div class="row">        
        {% include 'includes/profile-nav.html' %}  
        <div class="col-12 col-md-9 profile-main">
            <div class="container">                
                <div class="row">
                    <div class="col-8">
                        <h4 class="profile-header mb-3">Order Details</h4>                        
                    </div>                   
                </div>
                <div class="row">
                    <div class="col-12">
                        <p class="text-muted text-left">Order Number: <span class="order-number">{{ order.order_number }}</span></p>
                        <p class="text-muted text-left">Placed on {{ order.date }}</p>
                    </div>
                </div>
                <div class="row">
                    <div class="col-12">
                        <div class="d-block d-sm-none text-center">                
                            {% for item in order.lineitems.all %}
                                <div class="row">
                                    <div class="col-12 mb-2">
                                        {% include "profiles/product-image.html" %}
                                    </div>
                                    <div class="col-12 mb-2">
                                        {% include "profiles/product-info.html" %}
                                    </div>
                                    <div class="col-12 mb-2"> 
                                        <p class="my-0">Subtotal: €{{ item.product.price | calc_subtotal:item.quantity }}</p>
                                    </div>
                                    <div class="col-12 mb-2"> 
                                        <a href="{% url 'products:review_product' item.product.id order.id %}" class="btn btn-basic text-small">Leave a Review</a>
                                    </div>
                                </div>
                                <div class="row"><div class="col"><hr></div></div>
                            {% endfor %}
                            <div class="row">
                                <div class="col text-right">
                                    {% include "profiles/order-total.html" %}
                                </div>
                            </div>                                       
                        </div>
                        <div class="order-details table-responsive d-none d-sm-block">
                            <table class="table table-sm order-table">
                                <thead>
                                    <tr>
                                        <th>Image</th>
                                        <th>Product</th>
                                        <th></th>                                        
                                        <th>Quantity</th>
                                        <th>Price</th>
                                        <th>Total</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for item in order.lineitems.all %}
                                    <tr>
                                        <td class="w-25">                                        
                                            {% if item.product.image %}
                                            <img class="card-img-top w-50 img-fluid" src="{{ item.product.image.url }}" alt="{{ product.name }}">
                                            {% else %}
                                           <img class="card-img-top w-50 img-fluid" src="{{ MEDIA_URL }}noimage.png" alt="{{ product.name }}">
                                            {% endif %}
                                            </td>
                                        <td>{{ item.product.name }}</td>                                       
                                        <td><a href="{% url 'products:review_product' item.product.id order.id %}" class="btn btn-basic text-small">Leave a Review</a></td>
                                        <td>{{ item.quantity }}</td>
                                        <td>€{{ item.product.price }}</td>                                               
                                        <td>€{{ item.product.price | calc_subtotal:item.quantity }}</td>
                                    </tr>
                                    {% endfor %}
                                    <tr>
                                        <td colspan="6" class="text-right">
                                            <p class="mb-1">Total: €{{ order.order_total }}</p>
                                            <p class="mb-1">Shipping: €{{ order.shipping_cost }}</p>
                                            <p class="mb-1"><strong>Grand Total: €{{ order.grand_total }}</strong></p>
                                        </td>
                                    </tr>
                                </tbody>
                            </table>                            
                        </div>
                        <div class="text-left mt-3">
                            <a href="{% url 'profile:orders' %}" class="arrow-back profile-links">
                            <i class="fa fa-angle-double-left "></i> Back to Orders</a>
                        </div>
                    </div>                
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock %}

profiles/templates/profiles/orders.html
{% extends "base.html" %}
{% load static %}

{% block extra_css %}
    <link rel="stylesheet" href="{% static 'profiles/css/profile.css' %}">
{% endblock %}

{% block page_header %}
    <div class="container header-container">
        <div class="row text-center">
            <div class="col-12 mt-2 my-auto py-2">
                <h3 class="top-products-link">My Profile</h3>
                <hr> 
            </div>
        </div>
    </div>    
{% endblock %}

{% block content %}
<div class="container main text-center">
    <div class="row">        
        {% include 'includes/profile-nav.html' %}  
        <div class="col-12 col-lg-6 profile-main">
            <div class="container">                
                <div class="row">
                    <div class="col-12">
                        <h4 class="profile-header mb-3">Order History</h4>                        
                    </div>                   
                </div>               
                <div class="row"> 
                    <div class="col-12">                       
                        <div class="order-history table-responsive">
                            {% if orders %}
                            <table class="table table-sm table-borderless">
                                <thead>
                                    <tr>
                                        <th>Order Number</th>
                                        <th>Date</th>                                        
                                        <th>Order Total</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for order in orders %}
                                        <tr>
                                            <td>
                                                <a href="{% url 'profile:order_details' order.id %}"
                                                title="{{ order.order_number }}">
                                                    {{ order.order_number|truncatechars:6 }}
                                                </a>
                                            </td>
                                            <td>{{ order.date|date:'d M Y' }}</td>                                            
                                            <td>€{{ order.grand_total }}</td>
                                        </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                            {% else %}
                            <p>You have no orders yet.</p>
                            <a href="{% url 'products:products' %}" class="btn btn-basic mt-2">Place an order</a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock %}

profiles/templates/profiles/product-image.html
{% if item.product.image %}
<img class="img-fluid rounded" src="{{ item.product.image.url }}" alt="{{ item.product.name }}" width="100" height="100">
{% else %}
<img class="img-fluid rounded" src="{{ MEDIA_URL }}noimage.png" alt="{{ item.product.name }}">
{% endif %}

profiles/templates/profiles/product-info.html
<p class="my-0"><strong>{{ item.product.name }}</strong></p>
<p class="my-0"><strong>Quantity: {{ item.quantity }}</strong></p>
<p class="my-0">Price Each: €{{ item.product.price }}</p>

profiles/templates/profiles/shipping_addresses.html
{% extends "base.html" %}
{% load static %}

{% block extra_css %}
    <link rel="stylesheet" href="{% static 'profiles/css/profile.css' %}">
{% endblock %}

{% block page_header %}
    <div class="container header-container">
        <div class="row text-center">
            <div class="col-12 mt-2 my-auto py-2">
                <h3 class="top-products-link">My Profile</h3>
                <hr> 
            </div>
        </div>
    </div>    
{% endblock %}

{% block content %}
<div class="container main text-center">
    <div class="row">        
        {% include 'includes/profile-nav.html' %}  
        <div class="col-12 col-lg-8 profile-main">
            <div class="container">                
                <div class="row">
                    <div class="col-12 ">
                        <h4 class="profile-header mb-3 text-center">Shipping Addresses</h4>                        
                    </div>
                    <div class="col-12 profile-main mb-3">
                        <a href="{% url 'profile:add_address' %}" class="btn btn-basic mt-2 ml-3">Add new address</a>                         
                    </div>
                </div>               
                <div class="row justify-content-center">   
                    {% for address in addresses %} 
                    <div class="col-12 col-md-6 col-lg-4 mt-2 mb-2">                              
                        <div class="card h-100 border border-grey">
                            <div class="card-body">                                                                   
                                    <p class="text-left">{{ address.profile_street_address1 | capfirst }}</p>
                                    {% if address.profile_street_address2 != None %}
                                        <p class="text-left">{{ address.profile_street_address2 | capfirst  }}</p>
                                    {% endif %}
                                    <p class="text-left">{{ address.profile_city | capfirst  }}</p>
                                    <p class="text-left">{{ address.profile_county | capfirst }}</p>                                   
                                    {% if address.profile_postcode != None %}
                                        <p class="text-left">{{ address.profile_postcode }}</p>
                                    {% endif %}
                                    {% if address.profile_country == 'IE' %}
                                        <p class="text-left">Ireland</p>
                                    {% endif %}
                            </div>                                  
                            <div class="card-footer">                                      
                                {% if address.is_default %}
                                <h6 class="text-left mt-3 text-uppercase">Default address</h6>
                                {% else %}
                                <a href="{% url 'profile:edit_address' address.id %}" class="btn btn-basic text-small mt-2 card-link">Edit</a>
                                <a href="{% url 'profile:delete_address' address.id %}" class="btn btn-basic text-small mt-2 ml-2">Delete</a>
                                {% endif %}         
                            </div>
                        </div>                
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}