cart/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.view_cart, name='view_cart'),
    path('add/<item_id>/', views.add_to_cart, name='add_to_cart'),
    path('adjust_cart/<item_id>/', views.adjust_cart, name='adjust_cart'),
    path('delete/<item_id>/', views.delete_from_cart, name='delete_from_cart'),
]

checkout/urls.py
from django.urls import path
from . import views
from .webhooks import webhook


urlpatterns = [
    path('', views.checkout, name='checkout'),
    path('pre_checkout/', views.pre_checkout, name='pre_checkout'),
    path('checkout_success/<order_number>', views.checkout_success,
         name='checkout_success'),
    path('cache_checkout_data/', views.cache_checkout_data,
         name='cache_checkout_data'),
    path('wh/', webhook, name='webhook'),
]

products/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from . import views
from .views import ProductListView, CategoryView, ReviewView

app_name = 'products'

urlpatterns = [
    path('', ProductListView.as_view(), name='products'),
    path('category/<str:slug>/', CategoryView, name='category'),
    path('<int:product_id>/', views.product_detail, name='product_detail'),
    path('add/', views.add_product, name='add_product'),
    path('edit/<int:product_id>', views.edit_product, name='edit_product'),
    path('delete/<int:product_id>', views.delete_product,
         name='delete_product'),
    path('review_product/<int:product_id>/<int:order_id>/',
         login_required(ReviewView.as_view()), name='review_product'),
    path('show_reviews/', views.show_reviews, name='show_reviews'),
    path('approve_review/<int:product_id>/<int:review_id>/',
         views.approve_review, name='approve_review'),
]

t_studio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('core.urls')),
    path('products/', include(('products.urls'), namespace='products')),
    path('cart/', include('cart.urls')),
    path('checkout/', include('checkout.urls')),
    path('profile/', include(('profiles.urls'), namespace='profile')),
    path('contact/', include('contact.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = 't_studio.views.handler404'
handler500 = 't_studio.views.handler500'

checkout/models.py
import uuid
from django.db import models
from django.db.models import Sum
from django.core.validators import RegexValidator
from django.core.exceptions import ValidationError

from products.models import Product
from cart.models import Shipping
from profiles.models import UserProfile, UserAddress


def clean_full_name(value):
    if len(value.split()) < 2:
        raise ValidationError("Please enter your full name")
    return value


class Order(models.Model):

    order_number = models.CharField(max_length=32, null=False, editable=False)
    user_profile = models.ForeignKey(
        UserProfile, on_delete=models.SET_NULL,
        null=True, blank=True, related_name='orders')
    full_name = models.CharField(
        validators=[clean_full_name], max_length=50, null=False, blank=False)
    email = models.EmailField(max_length=254, null=False, blank=False)
    phone_regex = RegexValidator(
        regex=r'^(\+\d{1,3})?,?\s?\d{7,15}$',
        message="Please enter a correct phone number. "
                "Up to 15 digits without spaces allowed.")
    phone_number = models.CharField(
        validators=[phone_regex], max_length=17, null=False, blank=False)
    country = models.CharField(
        max_length=50, default='IE', null=False, blank=False)
    postcode = models.CharField(max_length=20, null=True, blank=True)
    city = models.CharField(max_length=40, null=False, blank=False)
    street_address1 = models.CharField(max_length=80, null=False, blank=False)
    street_address2 = models.CharField(max_length=80, null=True, blank=True)
    county = models.CharField(max_length=80, choices=UserAddress.COUNTIES)
    date = models.DateTimeField(auto_now_add=True)
    shipping_cost = models.DecimalField(
        max_digits=6, decimal_places=2, null=False, default=0)
    order_total = models.DecimalField(
        max_digits=10, decimal_places=2, null=False, default=0)
    grand_total = models.DecimalField(
        max_digits=10, decimal_places=2, null=False, default=0)
    original_cart = models.TextField(null=False, blank=False, default='')
    stripe_pid = models.CharField(
        max_length=254, null=False, blank=False, default='')
    order_weight = models.IntegerField(null=True, blank=True)

    def _generate_order_number(self):
        """
        Generate a random, unique order number using UUID
        """
        return uuid.uuid4().hex.upper()

    def update_total(self):
        """
        Update grand total and shipping each time a line item is added,
        accounting for delivery costs.
        """
        self.order_total = self.lineitems.aggregate(
            Sum('lineitem_total'))['lineitem_total__sum'] or 0
        self.order_weight = self.lineitems.aggregate(
            Sum('lineitem_weight'))['lineitem_weight__sum'] or 0

        all_rates = Shipping.objects.order_by('order_weight')
        for r in all_rates:
            if r.order_weight > self.order_weight + 100:
                parcel_weight = r.order_weight
                break

        self.shipping_cost = Shipping.objects.filter(
            order_weight=parcel_weight).values_list('postal_rates').first()[0]
        if self.order_total:
            self.grand_total = self.order_total + self.shipping_cost
        else:
            self.grand_total = 0
            self.shipping_cost = 0
        self.save()

    def save(self, *args, **kwargs):
        """
        Override the original save method to set the order number
        if it hasn't been set already.
        """
        if not self.order_number:
            self.order_number = self._generate_order_number()
        super().save(*args, **kwargs)

    def __str__(self):
        return self.order_number


class OrderLineItem(models.Model):
    order = models.ForeignKey(Order, null=False, blank=False,
                              on_delete=models.CASCADE,
                              related_name='lineitems')
    product = models.ForeignKey(Product, null=False, blank=False,
                                on_delete=models.CASCADE)
    quantity = models.IntegerField(null=False, blank=False, default=0)
    lineitem_total = models.DecimalField(max_digits=6, decimal_places=2,
                                         null=False, blank=False,
                                         editable=False)
    lineitem_weight = models.IntegerField(null=False, blank=False,
                                          editable=False)

    def save(self, *args, **kwargs):
        """
        Override the original save method to set the lineitem total
        and update the order total.
        """
        self.lineitem_total = self.product.price * self.quantity
        self.lineitem_weight = self.product.weight * self.quantity
        super().save(*args, **kwargs)

    def __str__(self):
        return f'SKU {self.product.sku} on order {self.order.order_number}'

checkout/views.py
from django.shortcuts import (render,
                              redirect, reverse, get_object_or_404,
                              HttpResponse)
from django.http import HttpResponseRedirect
from django.views.decorators.http import require_POST
from django.contrib import messages
from django.conf import settings
from django.db.models.functions import Concat
from django.db.models import Value
from django.core.mail import EmailMessage
from django.template.loader import render_to_string
from django.utils.safestring import mark_safe

from .forms import OrderForm
from .models import Order, OrderLineItem
from products.models import Product
from profiles.models import UserProfile, UserAddress
from profiles.forms import ProfileForm
from cart.contexts import cart_contents

import stripe
import json


@require_POST
def cache_checkout_data(request):
    try:
        pid = request.POST.get('client_secret').split('_secret')[0]
        stripe.api_key = settings.STRIPE_SECRET_KEY
        stripe.PaymentIntent.modify(pid, metadata={
            'cart': json.dumps(request.session.get('cart', {})),
            'save_info': request.POST.get('save_info'),
            'username': request.user,
        })
        return HttpResponse(status=200)
    except Exception as e:
        messages.error(request, ('Sorry, your payment cannot be '
                                 'processed right now. Please try '
                                 'again later.'))
        return HttpResponse(content=e, status=400)


def pre_checkout(request):
    """
    If 'POST', all user's data is collected and passed
    to the checkout function with Stripe payment field
    """
    if request.method == 'POST':
        cart = request.session.get('cart', {})

        form_data = {
            'full_name': request.POST['full_name'],
            'email': request.POST['email'],
            'phone_number': request.POST['phone_number'],
            'country': 'IE',
            'postcode': request.POST['postcode'],
            'city': request.POST['city'],
            'street_address1': request.POST['street_address1'],
            'street_address2': request.POST['street_address2'],
            'county': request.POST['county'],
        }
        order_form = OrderForm(form_data)

        if order_form.is_valid():
            request.session['save_info'] = 'save-info' in request.POST
            request.session['full_name'] = order_form.cleaned_data['full_name']
            request.session['email'] = order_form.cleaned_data['email']
            request.session['phone_number'] = order_form.cleaned_data[
                'phone_number']
            request.session['country'] = order_form.cleaned_data['country']
            request.session['postcode'] = order_form.cleaned_data['postcode']
            request.session['city'] = order_form.cleaned_data['city']
            request.session['street_address1'] = order_form.cleaned_data[
                'street_address1']
            request.session['street_address2'] = order_form.cleaned_data[
                'street_address2']
            request.session['county'] = order_form.cleaned_data['county']
            return HttpResponseRedirect(reverse('checkout'))
        else:
            messages.error(request, 'There was an error with your form. \
                Please double check your information.')
    else:
        cart = request.session.get('cart', {})
        if not cart:
            messages.error(request,
                           "There's nothing in your cart at the moment")
            return redirect(reverse('products:products'))
        """
        If the user returns from the checkout page, the form is pre-populated
        with data from the session
        """
        back = request.GET.get('back')
        if back == 'true':
            form_data = {
                'full_name': request.session.get('full_name'),
                'email': request.session.get('email'),
                'phone_number': request.session.get('phone_number'),
                'country': request.session.get('country'),
                'postcode': request.session.get('postcode'),
                'city': request.session.get('city'),
                'street_address1': request.session.get('street_address1'),
                'street_address2': request.session.get('street_address2'),
                'county': request.session.get('county'),
            }
            order_form = OrderForm(form_data)
        elif request.user.is_authenticated:
            """
            For logged in user the form is pre-populated
            with data from the db
            """
            try:
                profile = UserProfile.objects.get(user=request.user)
                address = UserAddress.objects.filter(
                    username=profile, is_default=True).first()
                full_name = UserProfile.objects.annotate(full_name=Concat(
                    'first_name', Value(' '), 'last_name')).get(
                    user=request.user).full_name
                if address:
                    order_form = OrderForm(initial={
                        'full_name': full_name,
                        'email': request.user.email,
                        'phone_number': profile.phone_number,
                        'country': address.profile_country,
                        'postcode': address.profile_postcode,
                        'city': address.profile_city,
                        'street_address1': address.profile_street_address1,
                        'street_address2': address.profile_street_address2,
                        'county': address.profile_county,
                    })
                else:
                    order_form = OrderForm(initial={
                        'email': request.user.email,
                        'phone_number': profile.phone_number,
                        'full_name': full_name,
                    })

            except UserProfile.DoesNotExist:
                order_form = OrderForm()
        else:
            order_form = OrderForm()

    template = 'checkout/pre_checkout.html'
    context = {
        'order_form': order_form,
    }
    return render(request, template, context)


def checkout(request):
    stripe_public_key = settings.STRIPE_PUBLIC_KEY
    stripe_secret_key = settings.STRIPE_SECRET_KEY

    if request.method == 'POST':
        cart = request.session.get('cart', {})
        save_info = request.session.get('save_info')

        form_data = {
            'full_name': request.session.get('full_name'),
            'email': request.session.get('email'),
            'phone_number': request.session.get('phone_number'),
            'country': request.session.get('country'),
            'postcode': request.session.get('postcode'),
            'city': request.session.get('city'),
            'street_address1': request.session.get('street_address1'),
            'street_address2': request.session.get('street_address2'),
            'county': request.session.get('county'),
        }
        order_form = OrderForm(form_data)

        if order_form.is_valid():
            order = order_form.save(commit=False)
            pid = request.POST.get('client_secret').split('_secret')[0]
            order.stripe_pid = pid
            order.original_cart = json.dumps(cart)
            order.save()
            for item_id, item_data in cart.items():
                try:
                    product = Product.objects.get(id=item_id)
                    order_line_item = OrderLineItem(
                        order=order,
                        product=product,
                        quantity=item_data,
                    )
                    order_line_item.save()

                except Product.DoesNotExist:
                    messages.error(request, (
                        "One of the products in your cart wasn't "
                        "found in our database. "
                        "Please call us for assistance!")
                    )
                    order.delete()
                    return redirect(reverse('view_cart'))

            return redirect(reverse('checkout_success', args=[
                order.order_number]))
        else:
            messages.error(request, 'There was an error with your form. \
                Please double check your information.')

    else:
        cart = request.session.get('cart', {})
        save_info = request.session.get('save_info')

        form_data = {
            'full_name': request.session.get('full_name'),
            'email': request.session.get('email'),
            'phone_number': request.session.get('phone_number'),
            'country': request.session.get('country'),
            'postcode': request.session.get('postcode'),
            'city': request.session.get('city'),
            'street_address1': request.session.get('street_address1'),
            'street_address2': request.session.get('street_address2'),
            'county': request.session.get('county'),
        }
        order_form = OrderForm(form_data)
        if not cart:
            messages.error(request,
                           "There's nothing in your cart at the moment")
            return redirect(reverse('products:products'))

    if not stripe_public_key:
        messages.warning(request, ('Stripe public key is missing. '
                                   'Did you forget to set it in '
                                   'your environment?'))

    current_cart = cart_contents(request)
    total = current_cart['grand_total']
    stripe_total = round(total * 100)
    stripe.api_key = stripe_secret_key
    intent = stripe.PaymentIntent.create(
        amount=stripe_total,
        currency=settings.STRIPE_CURRENCY,
    )

    template = 'checkout/checkout.html'
    context = {
        'order_form': order_form,
        'save_info': save_info,
        'stripe_public_key': stripe_public_key,
        'client_secret': intent.client_secret,
    }

checkout/templates/checkout/checkout.html
{% extends "base.html" %}
{% load static %}
{% load cart_tools %}

{% block extra_css %}
    <link rel="stylesheet" href="{% static 'checkout/css/checkout.css' %}">
{% endblock %}

{% block page_header %}
    <div class="container header-container">
        <div class="row text-center">
            <div class="col-12 mt-2 my-auto">
                <h3 class="top-products-link">Checkout, Step 2</h3>
                <hr>
            </div>
        </div>
    </div>
{% endblock %}

{% block content %}
<div class="container mt-2"> 
    <div class="row">
        <div class="col-12 col-lg-6 order-last mb-5">
            <p class="text-muted">Order Summary ({{ product_count }})</p>
            <div class="row">
                <div class="col-7 offset-2">
                    <p class="mb-1 mt-0 small text-muted">Item</p>
                </div>
                <div class="col-3 offset-xs-2 offset-sm-0 text-right">
                    <p class="mb-1 mt-0 small text-muted">Subtotal</p>
                </div>
            </div>
            {% for item in cart_items %}
                <div class="row">
                    <div class="col-2 mb-1 img-box">
                        <a href="{% url 'products:product_detail' item.product.id %}">
                            {% if item.product.image %}
                                <img class="w-100" src="{{ item.product.image.url }}" alt="{{ product.name }}">
                            {% else %}
                                <img class="w-100" src="{{ MEDIA_URL }}noimage.png" alt="{{ product.name }}">
                            {% endif %}
                        </a>
                    </div>
                    <div class="col-7">
                        <p class="my-0"><strong>{{ item.product.name }}</strong></p>                        
                        <p class="my-0 small text-muted">Qty: {{ item.quantity }}</p>
                    </div>
                    <div class="col-xs-5 col-sm-3 text-right">
                        <p class="my-0 small text-muted ">€{{ item.product.price | calc_subtotal:item.quantity }}</p>
                    </div>
                </div>
            {% endfor %}
            <hr class="my-0">
            <div class="row text-black text-right">
                <div class="col-7 offset-2">
                    <p class="my-0">Order Total:</p>
                    <p class="my-0">Shipping costs:</p>
                    <p class="my-0">Grand Total:</p>
                </div>
                <div class="col-3">
                    <p class="my-0">€{{ total | floatformat:2 }}</p>
                    <p class="my-0">€{{ shipping_cost | floatformat:2 }}</p>
                    <p class="my-0"><strong>€{{ grand_total | floatformat:2 }}</strong></p>                    
                </div>
            </div>
        </div>
        <div class="col-12 col-lg-6">           
            <form action="{% url 'checkout' %}" method="POST" id="payment-form">
                {% csrf_token %}
                <fieldset class="d-none">                   
                    {{ order_form.full_name | as_crispy_field }}
                    {{ order_form.email | as_crispy_field }}
                    {{ order_form.phone_number | as_crispy_field }}
                    {{ order_form.street_address1 | as_crispy_field }}
                    {{ order_form.street_address2 | as_crispy_field }}
                    {{ order_form.city | as_crispy_field }}
                    {{ order_form.county | as_crispy_field }}
                    {{ order_form.postcode | as_crispy_field }}
                    {{ order_form.country | as_crispy_field }}                   
                </fieldset>              
                <fieldset class="px-3">                   
                    {% if save_info %}
                    <p class="d-none">
                        <label class="form-check-label" for="id-save-info">Save</label>
                        <input class="form-check-input ml-2 mr-0" type="checkbox" id="id-save-info" name="save-info" checked>
                    </p>
                    {% endif %}
                    <legend class="fieldset-label small px-2 w-auto payment-label"><h4>Payment</h4></legend>
                    <!-- A Stripe card element will go here -->
                    <div class="mb-3" id="card-element"></div>
                    <!-- Used to display form errors -->
                    <div class="mb-3 text-danger" id="card-errors" role="alert"></div>
                    <!-- Pass the client secret to the view so we can get the payment intent id -->
                    <input type="hidden" value="{{ client_secret }}" name="client_secret">
                    <p class="small text-danger my-0">
                        <span class="icon">
                            <i class="fas fa-exclamation-circle"></i>
                        </span>
                        <span>Your card will be charged <strong>€{{ grand_total|floatformat:2 }}</strong></span>
                    </p>
                </fieldset>

                <div class="submit-button text-right mt-5 mb-2 mr-3">                    
                    <a href="{% url 'pre_checkout' %}?back=true" class="btn btn-basic mr-3 btn-order">
                        <span class="icon">
                            <i class="fas fa-chevron-left"></i>
                        </span>
                        <span class="text-uppercase">Back</span>
                    </a>
                    <button type="submit" id="submit-button" class="btn btn-basic btn-order btn-right">
                        <span class="text-uppercase">Complete Order</span>
                        <span class="icon">
                            <i class="fas fa-lock"></i>
                        </span>
                    </button>                   
                </div>
            </form>           
        </div>
    </div>
</div>
<div id="loading-overlay">
    <h1 class="text-light logo-font loading-spinner">
        <span class="icon">
            <i class="fas fa-3x fa-sync-alt fa-spin"></i>
        </span>
    </h1>
</div>

{% endblock %}

{% block postloadjs %}
    {{ block.super }}
    {{ stripe_public_key|json_script:"id_stripe_public_key" }}
    {{ client_secret|json_script:"id_client_secret" }}
    <script src="{% static 'checkout/js/stripe_elements.js' %}"></script>
{% endblock %}

checkout/templates/checkout/pre_checkout.html
{% extends "base.html" %}
{% load static %}
{% load cart_tools %}

{% block extra_css %}
    <link rel="stylesheet" href="{% static 'checkout/css/checkout.css' %}">
{% endblock %}

{% block page_header %}
    <div class="container header-container">
        <div class="row text-center">
            <div class="col-12 mt-2 my-auto">
                <h3 class="top-products-link">Checkout, Step 1</h3>
                <hr>
            </div>
        </div>
    </div>
{% endblock %}

{% block content %}
<div class="container mt-2">
    <div class="row">
        <div class="col-12 col-lg-6 order-lg-last mb-5">
            <p class="text-muted">Order Summary ({{ product_count }})</p>
            <div class="row">
                <div class="col-7 offset-2">
                    <p class="mb-1 mt-0 small text-muted">Item</p>
                </div>
                <div class="col-3 offset-xs-2 offset-sm-0 text-right">
                    <p class="mb-1 mt-0 small text-muted">Subtotal</p>
                </div>
            </div>
            {% for item in cart_items %}
                <div class="row">
                    <div class="col-2 mb-1 img-box">
                        <a href="{% url 'products:product_detail' item.product.id %}">
                            {% if item.product.image %}
                                <img class="w-100" src="{{ item.product.image.url }}" alt="{{ product.name }}">
                            {% else %}
                                <img class="w-100" src="{{ MEDIA_URL }}noimage.png" alt="{{ product.name }}">
                            {% endif %}
                        </a>
                    </div>
                    <div class="col-7">
                        <p class="my-0"><strong>{{ item.product.name }}</strong></p>
                        <p class="my-0 small text-muted">Qty: {{ item.quantity }}</p>
                    </div>
                    <div class="col-xs-5 col-sm-3 text-right">
                        <p class="my-0 small text-muted ">€{{ item.product.price | calc_subtotal:item.quantity }}</p>
                    </div>
                </div>
            {% endfor %}
            <hr class="my-0">
            <div class="row text-black text-right">
                <div class="col-7 offset-2">
                    <p class="my-0">Order Total:</p>
                    <p class="my-0">Shipping costs:</p>
                    <p class="my-0">Grand Total:</p>
                </div>
                <div class="col-3">
                    <p class="my-0">€{{ total | floatformat:2 }}</p>
                    <p class="my-0">€{{ shipping_cost | floatformat:2 }}</p>
                    <p class="my-0"><strong>€{{ grand_total | floatformat:2 }}</strong></p>
                </div>
            </div>
        </div>
        <div class="col-12 col-lg-6">
            <p class="text-muted">Please fill out the form below to complete your order<br>
                <strong>(for the Republic of Ireland only!)</strong></p>
            <form action="{% url 'pre_checkout' %}" method="POST">
                {% csrf_token %}
                <fieldset class="rounded px-3 mb-3">
                    <legend class="fieldset-label small w-auto"><h4>Details</h4></legend>
                    {{ order_form.full_name | as_crispy_field }}
                    {{ order_form.email | as_crispy_field }}
                </fieldset>
                <fieldset class="rounded px-3 mb-3">
                    <legend class="fieldset-label small w-auto"><h4>Shipping</h4></legend>
                    {{ order_form.phone_number | as_crispy_field }}
                    {{ order_form.street_address1 | as_crispy_field }}
                    {{ order_form.street_address2 | as_crispy_field }}
                    {{ order_form.city | as_crispy_field }}
                    {{ order_form.county | as_crispy_field }}
                    {{ order_form.postcode | as_crispy_field }}
                    {{ order_form.country | as_crispy_field }}
                    <div class="form-check form-check-inline float-right mr-0">
                        {% if user.is_authenticated %}
                            <label class="form-check-label" for="id-save-info">Save this shipping information to my profile</label>
                            <input class="form-check-input ml-2 mr-0" type="checkbox" id="id-save-info" name="save-info" checked>
                        {% else %}
                            <label class="form-check-label" for="id-save-info">
                                <a class="text-info" href="{% url 'account_signup' %}">Create an account</a> or
                                <a class="text-info" href="{% url 'account_login' %}">login</a> to save this information
                            </label>
                        {% endif %}
                    </div>
                </fieldset>
                <div class="submit-button text-right mt-5 mb-2">
                    <a href="{% url 'view_cart' %}" class="btn btn-basic mr-3 btn-order">
                        <span class="icon">
                            <i class="fas fa-chevron-left"></i>
                        </span>
                        <span class="text-uppercase">Adjust Cart</span>
                    </a>
                    <button type="submit" name="pre-submit" class="btn btn-basic btn-order btn-right">
                        <span class="text-uppercase">Next</span>
                        <span class="icon">
                            <i class="fas fa-chevron-right"></i>
                        </span>
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}