cart/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.view_cart, name='view_cart'),
    path('add/<item_id>/', views.add_to_cart, name='add_to_cart'),
    path('adjust_cart/<item_id>/', views.adjust_cart, name='adjust_cart'),
    path('delete/<item_id>/', views.delete_from_cart, name='delete_from_cart'),
]

products/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from . import views
from .views import ProductListView, CategoryView, ReviewView

app_name = 'products'

urlpatterns = [
    path('', ProductListView.as_view(), name='products'),
    path('category/<str:slug>/', CategoryView, name='category'),
    path('<int:product_id>/', views.product_detail, name='product_detail'),
    path('add/', views.add_product, name='add_product'),
    path('edit/<int:product_id>', views.edit_product, name='edit_product'),
    path('delete/<int:product_id>', views.delete_product,
         name='delete_product'),
    path('review_product/<int:product_id>/<int:order_id>/',
         login_required(ReviewView.as_view()), name='review_product'),
    path('show_reviews/', views.show_reviews, name='show_reviews'),
    path('approve_review/<int:product_id>/<int:review_id>/',
         views.approve_review, name='approve_review'),
]

t_studio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('core.urls')),
    path('products/', include(('products.urls'), namespace='products')),
    path('cart/', include('cart.urls')),
    path('checkout/', include('checkout.urls')),
    path('profile/', include(('profiles.urls'), namespace='profile')),
    path('contact/', include('contact.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = 't_studio.views.handler404'
handler500 = 't_studio.views.handler500'

products/models.py
from django.db import models
from profiles.models import UserProfile


class Category(models.Model):

    name = models.CharField(max_length=50)
    friendly_name = models.CharField(max_length=254, null=True, blank=True)
    description = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.name

    def get_friendly_name(self):
        return self.friendly_name

    class Meta:
        verbose_name_plural = 'Categories'


class Product(models.Model):
    category = models.ForeignKey('Category', null=True,
                                 blank=True, on_delete=models.SET_NULL)
    sku = models.CharField(max_length=10, unique=True)
    name = models.CharField(max_length=100)
    description = models.TextField()
    price = models.DecimalField(max_digits=6, decimal_places=2)
    discount = models.IntegerField(null=True, blank=True)
    stock = models.IntegerField(null=True, blank=True)
    in_stock = models.BooleanField(default=True)
    rating = models.FloatField(null=True, blank=True)
    image_url = models.URLField(max_length=1024, null=True, blank=True)
    image = models.ImageField(null=True, blank=True)
    weight = models.IntegerField(null=True, blank=True)

    def __str__(self):
        return f"{self.name}"


class Review(models.Model):
    """Model for user review"""

    RATE_CHOICES = [
        (5, 'Excellent'),
        (4, 'Very Good'),
        (3, 'Average'),
        (2, 'Fair'),
        (1, 'Poor'),
    ]

    user = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE,
                                related_name="reviews", null=True, blank=True)
    author = models.CharField(max_length=50, null=False, blank=False)
    comment = models.TextField(null=False, blank=False)
    rate = models.IntegerField(choices=RATE_CHOICES, default=None)
    created_at = models.DateTimeField(auto_now_add=True)
    approved = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.product.name}, {self.rate}"

products/forms.py
from django import forms
from .models import Review, Product, Category
from .widgets import CustomClearableFileInput


class ProductForm(forms.ModelForm):

    class Meta:
        model = Product
        exclude = ('rating',)

        widgets = {
            'price': forms.NumberInput(attrs={'min': 1, 'max': 1000}),
            'discount': forms.NumberInput(attrs={'min': 1, 'max': 100}),
            'weight': forms.NumberInput(attrs={'min': 1, 'max': 10000}),
            'stock': forms.NumberInput(attrs={'min': 0, 'max': 10000}),
        }

    image = forms.ImageField(label='Image', required=False,
                             widget=CustomClearableFileInput)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        categories = Category.objects.all()
        friendly_names = [(c.id, c.get_friendly_name()) for c in categories]

        self.fields['weight'].required = True
        self.fields['category'].choices = friendly_names


class ReviewForm(forms.ModelForm):

    class Meta:
        model = Review
        fields = ('author', 'comment', 'rate')

        widgets = {
            'author': forms.TextInput(attrs={'class': 'form-control'}),
            'comment': forms.Textarea(attrs={'class': 'form-control',
                                             'maxlength': 1000}),
            'rate': forms.RadioSelect(attrs={'class': 'form-check-inline'}),
        }

products/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import ListView
from django.views.generic.edit import CreateView
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.db.models import Avg

from .models import Product, Category, Review
from checkout.models import Order
from .forms import ReviewForm, ProductForm


class ProductListView(ListView):
    """A Class Based View to show all products, including search queries,
    to check average product rating and save it to DB if changed"""
    model = Product
    template_name = 'products/products.html'
    context_object_name = 'products'

    def get(self, request, *args, **kwargs):
        for product in Product.objects.all():
            approved_reviews = Review.objects.filter(
                product_id=product.id, approved=True)
            avg = approved_reviews.aggregate(Avg('rate'))['rate__avg']
            if avg is not None:
                rounded_avg = 0.5 * round(avg/0.5)
                if product.rating != rounded_avg:
                    product.rating = rounded_avg
                    product.save()
            else:
                product.rating = None
                product.save()
        response = super().get(request, *args, **kwargs)
        return response

    def get_queryset(self):
        queryset = super(ProductListView, self).get_queryset(
                   ).order_by('name')
        q = self.request.GET.get('q')
        if q:
            queryset = self.model.objects.filter(
                Q(name__icontains=q) | Q(description__icontains=q)
                )
        return queryset

    def get_context_data(self, object_list=None, **kwargs):
        context = super(ProductListView, self).get_context_data()
        context['categories'] = Category.objects.all()
        context['q'] = self.request.GET.get('q')
        return context


def CategoryView(request, slug):
    """A view to get all product categories and
    products by current category
    """
    try:
        current_category = Category.objects.get(name=slug)
        category_products = Product.objects.filter(
            category=current_category).order_by('name')
        all_categories = Category.objects.all()
        context = {
            'category_products': category_products,
            'slug': slug,
            'categories': all_categories
        }
        return render(request, 'products/products.html', context)
    except Category.DoesNotExist:
        messages.error(request, "That category doesn't exist")
        return redirect('products:products')


def product_detail(request, product_id):
    """A view to show individual product details"""
    product = get_object_or_404(Product, pk=product_id)
    category = Category.objects.filter(product=product)
    reviews = Review.objects.filter(
            product_id=product.id, approved=True)
    context = {
        "product": product,
        "category": category,
        "reviews": reviews,
    }
    return render(request, "products/product_detail.html", context)


@login_required
def add_product(request):
    """ Add a product to the store """
    if not request.user.is_superuser:
        messages.error(request, 'Sorry, only store owners can do that.')
        return redirect(reverse('core'))

    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            product = form.save()
            messages.success(request,
                             'Successfully added product!',
                             extra_tags='flag')
            return redirect(reverse(
                'products:product_detail', args=[product.id]))
        else:
            messages.error(request,
                           'Failed to add product. '
                           'Please ensure the form is valid.')
    else:
        form = ProductForm()

    template = 'products/add_product.html'
    context = {
        'form': form,
    }
    return render(request, template, context)


@login_required
def edit_product(request, product_id):
    """ Edit a product in the store """
    if not request.user.is_superuser:
        messages.error(request, 'Sorry, only store owners can do that.')
        return redirect(reverse('core'))

    product = get_object_or_404(Product, pk=product_id)
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES, instance=product)
        if form.is_valid():
            form.save()
            messages.success(request,
                             'Successfully updated product!',
                             extra_tags='flag')
            return redirect(reverse(
                'products:product_detail', args=[product.id]))
        else:
            messages.error(request,
                           'Failed to update product. '
                           'Please ensure the form is valid.')
    else:
        form = ProductForm(instance=product)
        messages.info(request, f'You are editing {product.name}')

    template = 'products/edit_product.html'
    context = {
        'form': form,
        'product': product,
    }
    return render(request, template, context)


@login_required
def delete_product(request, product_id):
    """ Delete a product from the store """
    if not request.user.is_superuser:
        messages.error(request, 'Sorry, only store owners can do that.')
        return redirect(reverse('core'))
    product = get_object_or_404(Product, pk=product_id)
    delete_product = request.GET.get('delete_product')
    if product:
        if delete_product:
            product.delete()
            messages.success(request, 'Product deleted!', extra_tags='flag')
            return redirect('products:products')
        else:
            template = 'products/delete_product.html'
            context = {
                'product': product,
                'flag': True,
            }
            return render(request, template, context)
    else:
        messages.error(request,
                       'Sorry, product not exists.')
        return redirect(reverse('products:products'))


class ReviewView(SuccessMessageMixin, CreateView):
    """A Class Based View to get product review from
    the user and redirect him to order history page
    """
    model = Review
    form_class = ReviewForm
    template_name = 'products/review_product.html'
    success_url = '/order_details/'

    def get_success_url(self):
        return reverse('profile:order_details', kwargs={
                       'order_id': self.kwargs['order_id']})

    def form_valid(self, form):
        form.instance.user = self.request.user.userprofile
        form.instance.product_id = self.kwargs['product_id']
        success_message = ("Thank you for the review! "
                           "It will be published after admin approval.")
        extra_tags = 'flag'
        messages.success(self.request, success_message, extra_tags=extra_tags)
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['product'] = get_object_or_404(
            Product, pk=self.kwargs['product_id'])
        context['order_id'] = get_object_or_404(
            Order, user_profile=self.request.user.userprofile,
            id=self.kwargs['order_id'])
        return context


@login_required
def show_reviews(request):
    """ Display all not approved reviews to admin """
    if not request.user.is_superuser:
        messages.error(request,
                       'Sorry, only store owners can access this page.')
        return redirect(reverse('core'))
    reviews = Review.objects.filter(approved=False)
    template = 'products/show_reviews.html'
    context = {
        'reviews': reviews,
    }
    return render(request, template, context)


@login_required
def approve_review(request, product_id, review_id):
    """ View to approve review by admin and
    to calculate average product rating"""
    if not request.user.is_superuser:
        messages.error(request,
                       'Sorry, only store owners can access this page.')
        return redirect(reverse('core'))
    r_to_approve = Review.objects.get(product_id=product_id, id=review_id)
    r_to_approve.approved = True
    r_to_approve.save()
    """ Calculate and save to DB average product rating"""
    product = Product.objects.get(pk=product_id)
    approved_reviews = Review.objects.filter(
        product_id=product_id, approved=True)
    avg = approved_reviews.aggregate(Avg('rate'))['rate__avg']
    rounded_avg = 0.5 * round(avg/0.5)
    product.rating = rounded_avg
    product.save()
    return redirect('products:show_reviews')

products/templates/products/add_product.html
{% extends "base.html" %}
{% load static %}
{% load cart_tools %}

{% block extra_css %}
    <link rel="stylesheet" href="{% static 'checkout/css/checkout.css' %}">
{% endblock %}

{% block page_header %}
    <div class="container header-container">
        <div class="row text-center">
            <div class="col-12 mt-2 my-auto">
                <h3 class="top-products-link">Product Management</h3>
                <h4 class="top-products-link text-muted">Add a Product</h4>
            </div>
        </div>
    </div>
{% endblock %}

{% block content %}
<div class="container mt-2"> 
    <div class="row justify-content-center">
        <div class="col-12 col-md-6">
            <form method="POST" action="{% url 'products:add_product' %}" class="form mb-2" enctype="multipart/form-data">
                {% csrf_token %}
                {% for field in form %}
                    {% if field.name != 'image' %}
                        {{ field | as_crispy_field }}
                    {% else %}
                        {{ field }}
                    {% endif %}
                {% endfor %}
                <div class="text-right">
                    <button class="btn btn-basic" type="submit">Add Product</button>
                    <a class="btn btn-cancel ml-3" href="{% url 'products:products' %}">Cancel</a>                    
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

{% block postloadjs %}
    {{ block.super }}
    <script type="text/javascript">
        $('#new-image').change(function() {
            var file = $('#new-image')[0].files[0];
            $('#filename').text(`Image will be set to: ${file.name}`);
        });
    </script>
{% endblock %}

products/templates/products/product_detail.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
<div class="container header-container">
    <div class="row">
        <div class="col"></div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-12 col-md-6 col-lg-4 offset-lg-2">
            <div class="image-container my-5">
                {% if product.image %}
                    <img class="card-img-top img-fluid" src="{{ product.image.url }}" alt="{{ product.name }}">
                {% else %}
                    <img class="card-img-top img-fluid" src="{{ MEDIA_URL }}noimage.png" alt="{{ product.name }}">
                {% endif %}
            </div>
        </div>
        <div class="col-12 col-md-6 col-lg-4">
            <div class="product-details-container mb-5 mt-md-5">
                    <h4 class="mb-0 font-weight-bold">{{ product.name }}</h4>
                <p class="mb-0 text-left"><strong>Price: €{{ product.price }}</strong></p>
                <p class="mt-1 mb-0">
                    <a class="text-muted" href="{% url 'products:category' product.category.name %}">
                        <i class="fas fa-tag mr-1"></i>{{ product.category }}
                    </a>
                </p>
                {% if product.rating %}
                    Rating: {{ product.rating }}
                    {% with product.rating as r %}
                        {% if r > 0 and r != 0.5  %} <i class='fa fa-star text-muted'></i>
                        {% elif r == 0.5 %}<i class='fa fa-star-half-o text-muted'></i>
                        {% else %} <i class='fa fa-star-o text-muted'></i> {% endif %}
                        {% if r > 1 and r != 1.5 %} <i class='fa fa-star text-muted'></i>
                        {% elif r == 1.5 %}<i class='fa fa-star-half-o text-muted'></i>
                        {% else %} <i class='fa fa-star-o text-muted'></i> {% endif %}
                        {% if r > 2 and r != 2.5 %} <i class='fa fa-star text-muted'></i>
                        {% elif r == 2.5 %}<i class='fa fa-star-half-o text-muted'></i>
                        {% else %} <i class='fa fa-star-o text-muted'></i> {% endif %}
                        {% if r > 3 and r != 3.5 %} <i class='fa fa-star text-muted'></i>
                        {% elif r == 3.5 %}<i class='fa fa-star-half-o text-muted'></i>
                        {% else %} <i class='fa fa-star-o text-muted'></i> {% endif %}
                        {% if r > 4 and r != 4.5 %} <i class='fa fa-star text-muted'></i>
                        {% elif r == 4.5 %}<i class='fa fa-star-half-o text-muted'></i>
                        {% else %} <i class='fa fa-star-o text-muted'></i> {% endif %}
                    {% endwith %}
                {% else %}
                <small class="text-muted">No Rating</small>
                {% endif %}
                <p><br>
                    <small class="text-muted mt-1 ">Color: <strong>random</strong></small><br>
                {% if product.id != 13 %}
                    <small class="text-muted">5 types of needles: <strong>iron, copper, nickel, zinc, silver</strong></small>
                {% endif %}
                </p>
                {% if request.user.is_superuser %}
                <p>
                    <a class='btn btn-basic' href="{% url 'products:edit_product' product.id %}"><small>Edit</small></a>
                    <a class="btn btn-basic text-danger ml-3" href="{% url 'products:delete_product' product.id %}"><small>Delete</small></a>
                </p>
                {% endif %}
                <form class="form" action="{% url 'add_to_cart' product.id %}" method="POST">
                    {% csrf_token %}
                    <div class="form-row">
                        <div class="col-12">
                            <p class="mt-3"><strong>Quantity:</strong></p>
                            <div class="form-group w-25">
                                <div class="input-group input-group-{{ product.id }}">
                                    <input title="quantity" class="form-control qty_input id_qty_{{ product.id }}" type="number"
                                        name="quantity" value="1" min="1" max="99"
                                        data-item_id="{{ product.id }}">
                                </div>
                            </div>
                        </div>
                        <div class="col-12">
                            <a href="{% url 'products:products' %}" class="btn btn-cart btn-basic mt-2 ml-3">
                                <span class="icon">
                                    <i class="fas fa-chevron-left"></i>
                                </span>
                                <span class="text-uppercase">Keep Shopping</span>
                            </a>
                            <input type="submit" class="btn btn-basic btn-cart text-uppercase mt-2 ml-3" value="Add to Cart">
                        </div>
                        <input type="hidden" name="redirect_url" value="{{ request.path }}">
                    </div>
                </form>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-12 col-lg-8 offset-lg-2">
            {% autoescape off %}
            <h4>Description:</h4>
            <div class="mt-1">{{ product.description }}</div>
            {% endautoescape %}
        </div>
    </div>
    {% if reviews %}
        <div class="row">
            <div class="col-12 col-lg-8 offset-lg-2 mt-3">
                <h4>Reviews</h4>
                <hr>
            </div>
        </div>
        <div class="row">
            <div class="col-12 col-lg-8 offset-lg-2">
                {% for review in reviews %}
                    <strong>
                        {{ review.author }} -
                        {{ review.created_at }}
                    </strong><br>
                    {{ review.comment }}
                    <br>
                    <p>Rate:
                        {% if review.rate|add:'0' > 0 %} <span class="fa fa-star"></span>{% else %} <i class='fa fa-star-o text-muted'></i>{% endif %}
                        {% if review.rate|add:'0' > 1 %} <span class="fa fa-star"></span>{% else %} <i class='fa fa-star-o text-muted'></i>{% endif %}
                        {% if review.rate|add:'0' > 2 %} <span class="fa fa-star"></span>{% else %} <i class='fa fa-star-o text-muted'></i>{% endif %}
                        {% if review.rate|add:'0' > 3 %} <span class="fa fa-star"></span>{% else %} <i class='fa fa-star-o text-muted'></i>{% endif %}
                        {% if review.rate|add:'0' > 4 %} <span class="fa fa-star"></span>{% else %} <i class='fa fa-star-o text-muted'></i>{% endif %}
                    </p>
                <hr class="line-review">
                {% endfor %}
            </div>
        </div>
    {% endif %}
</div>
{% endblock %}

products/templates/products/products.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
<div class="container header-container">
    <div class="row text-center">
        <div class="col-12 mt-2 my-auto">
            <h3><a class="top-products-link" href="{% url 'products:products' %}">Applicators</a>{% if category_products %}  | {{ slug }}{% endif %}</h3> 
            {% for category in categories %}                         
                <a class="category-badge text-decoration-none" href="{% url 'products:category' category.name %}">
                    <span class="p-2 badge badge-category ">{{ category.friendly_name }}</span>
                </a>
            {% endfor %}            
            <hr> 
        </div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="container-fluid main">
    <div class="row">
        <div class="col-lg-6 col-sm-12 mb-2 d-flex justify-content-center">
            {% if q %}
                {% if products.count == 1 %}          
                1 Product found for &nbsp; <strong>"{{ q }}"</strong>
                {% else %}
                {{ products|length }} Products found for &nbsp; <strong>"{{ q }}"</strong>
                {% endif %}
            {% endif %}            
        </div>
    </div>
    <div class="row">
        <div class="col-lg-9 offset-1 mb-2 d-flex justify-content-end">
            <div class="search-block">
                <form method="GET" action="{% url 'products:products' %}">
                    <div class="input-group w-100">
                        <input class="border border-grey form-custom" type="text" name="q" placeholder="Search our store">
                        <div class="input-group-append">
                            <button title="search" class="btn-orange" type="submit">
                                <span class="icon">
                                    <i class="fas fa-search"></i>
                                </span>
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>   
    <div class="row justify-content-center">
        <div class="product-container h-100 col-10 mb-4">
            <div class="row product-row">
                {% if category_products %}
                {% for product in category_products %}               
                <div class="col-sm-6 col-md-6 col-lg-4 mt-2 mb-2">
                    <div class="card h-100 border border-grey product-align">
                        <a class='products-link' href="{% url 'products:product_detail' product.id %}">                           
                            {% if product.image %}
                                <img class="card-img-top product-image" src="{{ product.image.url }}"  alt="{{product.product_name}}">
                            {% else %}
                                <img class="card-img-top product-image" src="{% static 'images/noimage.png' %}" alt="{{product.product_name}}">
                            {% endif %}                                              
                            <div class="card-body pb-0">
                                <h5 class="mb-0 font-weight-bold products-link">{{ product.name }}</h5>
                            </div>
                        </a> 
                        <div class="card-footer bg-white pt-0 border-0 text-left">
                            <div class="row">
                                <div class="col">
                                    <p class="lead mb-0 text-left font-weight-bold">€{{ product.price }}</p>
                                    {% if product.category %}
                                    <p class="small mt-1 mb-0">
                                        <a class="text-muted"
                                            href="{% url 'products:category' product.category.name %}">
                                            <i class="fas fa-tag mr-1"></i>{{ product.category.friendly_name }}
                                        </a>
                                    </p>
                                    {% endif %}
                                    {% if product.rating %}
                                    <small class="text-muted"><i class="fas fa-star mr-1"></i>{{ product.rating }} /
                                        5</small>
                                    {% else %}
                                    <small class="text-muted">No Rating</small>
                                    {% endif %}                                    
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %} 
            {% else %}
                {% for product in products %}
                <div class="col-sm-6 col-md-6 col-lg-4 mt-2 mb-2">
                    <div class="card h-100 border border-grey product-align">
                        <a class='products-link' href="{% url 'products:product_detail' product.id %}">                           
                            {% if product.image %}
                                <img class="card-img-top product-image" src="{{ product.image.url }}"  alt="{{product.product_name}}">
                            {% else %}
                                <img class="card-img-top product-image" src="{% static 'images/noimage.png' %}" alt="{{product.product_name}}">
                            {% endif %}                                              
                            <div class="card-body pb-0">
                                <h5 class="mb-0 font-weight-bold products-link">{{ product.name }}</h5>
                            </div>
                        </a> 
                        <div class="card-footer bg-white pt-0 border-0 text-left">
                            <div class="row">
                                <div class="col">
                                    <p class="lead mb-0 text-left font-weight-bold">€{{ product.price }}</p>
                                    {% if product.category %}
                                    <p class="mt-1 mb-0">
                                        <a class="text-muted"
                                            href="{% url 'products:category' product.category.name %}">
                                            <i class="fas fa-tag mr-1"></i>{{ product.category.friendly_name }}
                                        </a>
                                    </p>
                                    {% endif %}
                                    {% if product.rating %}
                                    <small class="text-muted"><i class="fas fa-star mr-1"></i>
                                    {{ product.rating }} / 5</small>
                                    {% else %}
                                    <small class="text-muted">No Rating</small>
                                    {% endif %}
                                    {% if request.user.is_superuser %}
                                        <p>
                                            <a class='btn btn-basic mt-3' href="{% url 'products:edit_product' product.id %}"><small>Edit</small></a> 
                                            <a class="btn btn-basic text-danger ml-3 mt-3" href="{% url 'products:delete_product' product.id %}"><small>Delete</small></a>
                                        </p>
                                    {% endif %}                                    
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}   
            {% endif %}       
            </div>
        </div> 
    </div>  
</div>
{% endblock %}